<script lang="ts">
import { enhance } from '$app/forms';
import type { PageProps } from './$types';
let { data, form }: PageProps = $props();
const d = $derived(data.dashboard);
const fields = [['baseline_hours_month','Waktu baseline / bulan (jam)',50],['new_work_hours_month','Waktu kerja baru / bulan (jam)',12],['review_hours_month','Waktu review / bulan (jam)',6],['correction_hours_month','Waktu koreksi / bulan (jam)',2],['value_per_hour','Nilai kapasitas / jam (Rp)',100000],['monthly_operating_cost','Biaya operasional / bulan (Rp)',1500000],['initial_cost','Investasi awal (Rp)',12000000],['horizon_months','Horizon (bulan)',12]];
</script>
<svelte:head><title>Laporan & ROI — Campus Assistant</title></svelte:head>
<main><nav><a href="/">CA · Campus Assistant</a><div><a href={d ? `/?class=${encodeURIComponent(d.id)}` : '/'}>Ringkasan</a><a href={d ? `/academic?class=${encodeURIComponent(d.id)}` : '/academic'}>Data Akademik</a></div></nav><header><p>LAPORAN & EKSPOR</p><h1>Capaian yang dapat ditelusuri.</h1><form method="GET"><label>Pilih kelas<select name="class" onchange={e => e.currentTarget.form?.requestSubmit()}>{#each data.classes as c}<option value={c.id} selected={c.id === d?.id}>{c.name}</option>{/each}</select></label></form></header>{#if data.error || form?.error}<div class="alert" role="alert">{data.error || form?.error}</div>{/if}{#if d}<article><div class="heading"><div><h2>Laporan CPMK dan CPL</h2><p>{d.name} · Cakupan mata kuliah, bukan keseluruhan prodi.</p></div><a class="button" href={`/reports/export?class=${encodeURIComponent(d.id)}`}>Unduh CSV ↓</a></div><div class="scroll"><table><thead><tr><th>Mahasiswa</th><th>Outcome</th><th>Capaian</th><th>Target</th><th>Status</th></tr></thead><tbody>{#each d.students as s}{#each [...s.cpmks,...s.cpls] as c}<tr><td>{s.name}<small>{s.id}</small></td><td>{c.id}</td><td>{c.score ?? 'Belum lengkap'}</td><td>{c.target}</td><td><span class:gap={c.status==='gap'}>{c.status==='achieved' ? 'Target tercapai' : c.status==='gap' ? 'Learning gap' : 'Data belum lengkap'}</span></td></tr>{/each}{/each}</tbody></table></div></article><article><h2>Kalkulator skenario ROI</h2><p>Angka awal adalah ilustrasi yang dapat Anda ubah. Hasil merupakan manfaat kapasitas dan tidak otomatis menjadi penghematan kas atau keputusan GO.</p><form method="POST" action="?/scenario" use:enhance><input type="hidden" name="class_id" value={d.id}/><div class="grid">{#each fields as [key,label,value]}<label>{label}<input name={String(key)} type="number" min={key==='horizon_months' ? 1 : 0} step={key==='horizon_months' ? 1 : 0.01} value={Number(value)} required/></label>{/each}</div><button class="button">Hitung skenario</button></form>{#if form?.scenario}<div class="results"><div><span>Jam bersih dihemat / bulan</span><strong>{form.scenario.metrics.net_hours_saved_month}</strong></div><div><span>Manfaat bersih / bulan</span><strong>Rp{Number(form.scenario.metrics.net_benefit_month_idr).toLocaleString('id-ID')}</strong></div><div><span>ROI selama horizon</span><strong>{form.scenario.metrics.horizon_roi_pct !== null ? `${Number(form.scenario.metrics.horizon_roi_pct).toFixed(2)}%` : 'Tidak terdefinisi'}</strong></div><div><span>Payback</span><strong>{form.scenario.metrics.payback_months !== null ? `${Number(form.scenario.metrics.payback_months).toFixed(1)} bulan` : 'Tidak tercapai'}</strong></div></div><p class="notice">Release tetap HOLD. Lengkapi evaluasi kualitas, keamanan dan manfaat tambahan AI sebelum perluasan.</p>{/if}</article>{/if}</main>
<style>
:global(body){background:#f5f7fb;color:#213650;font:14px Inter,system-ui,sans-serif;margin:0}:global(*){box-sizing:border-box}main{max-width:1200px;margin:auto;padding:25px}nav{display:flex;justify-content:space-between;background:white;padding:20px;border-radius:12px}nav div{display:flex;gap:20px}a{color:#0f4c9a;text-decoration:none}header{padding:30px 0}header>p{font-size:10px;letter-spacing:2px}h1{font-size:30px}h2{font-size:18px}p{color:#7a8da3;line-height:1.7}article{background:white;padding:25px;border:1px solid #e0e9f3;border-radius:14px;margin-bottom:24px}.heading{display:flex;justify-content:space-between;align-items:center;gap:15px}.button{display:inline-block;background:#0f4c9a;border:0;border-radius:8px;color:white;padding:12px 18px;font:inherit;cursor:pointer;margin-top:15px}label{display:grid;gap:7px;font-size:12px;color:#627d98}input,select{padding:11px;border:1px solid #dbe5f0;border-radius:8px;font:inherit}table{width:100%;text-align:left;border-collapse:collapse}th,td{padding:13px;border-bottom:1px solid #edf1f7;font-size:12px}th{color:#8194aa;background:#f8fafd}small{display:block;color:#8d9caf}.gap{color:#ad7729}.scroll{overflow:auto}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.results{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-top:24px}.results>div{background:#f0f7fc;padding:20px;border-radius:10px}.results span{font-size:11px;color:#748aa2}.results strong{display:block;color:#0f4c9a;font-size:21px;margin-top:10px}.notice{padding:15px;background:#edf8f2;color:#27865d;border-radius:8px}.alert{background:#fff0e9;padding:15px;color:#ad683c}@media(max-width:700px){main{padding:16px}.grid,.results{grid-template-columns:1fr 1fr}.heading{display:block}nav{font-size:11px;gap:10px}h1{font-size:25px}}@media print{nav,.button,article:last-child{display:none}main{padding:0}article{border:0}}
</style>
